Fix "multiple default values" error in migration
When migrating a fresh project, I received this error:

> psycopg2.errors.SyntaxError: multiple default values
> specified for column "id" of table "ii_ga_authorities"

It seems as if specifying an explicit default and setting
a column as a primary key are in conflict. Removing the
`default=1` line allowed the migration to proceed.